version: '3.8'

services:

  mongo:
    image: mongo:4.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
