version: '3.8'

services:

  mongo:
    image: mongo:4.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  app:
    build:
      context: .
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    depends_on:
      - mongo
